version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/app/chroma_db
    environment:
      - OPENAIAPIKEY_HACK=${OPENAIAPIKEY_HACK}
    restart: unless-stopped

volumes:
  chroma_data:
