version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/app/chroma_db
    environment:
      - OPENAI_API_KEY_HACK=${OPENAI_API_KEY_HACK}
    restart: unless-stopped

volumes:
  chroma_data:
